# R4OS standard QEMU config.
# CPU, RAM, SMP, display and serial are selected by the common PS7 runner.

[machine]
  type = "q35"

[drive "r4osboot"]
  file = "disk.img"
  if = "none"
  format = "raw"
  cache = "none"
  id = "r4osboot"

[device "ahci-controller"]
  driver = "ich9-ahci"
  id = "ahci0"

[device "boot-disk"]
  driver = "ide-hd"
  drive = "r4osboot"
  bus = "ahci0.0"
  unit = "0"

[device "audio-controller"]
  driver = "ich9-intel-hda"

[device "audio-codec"]
  driver = "hda-duplex"
